#!/bin/sh -e
# ============================================
#  splice_all - Controls the services splice depends on 
# ============================================
#
# :Usage: /etc/init.d/report-server {start|stop|restart|status}
#

LOG_FILE=/var/log/splice/report_server.log

#
# Hack to force the django log file is writeable by apache
# 
force_log_perms() {
    if [ -f ${LOG_FILE} ] 
    then
        touch ${LOG_FILE}
    fi
    chown -R apache:apache ${LOG_FILE}
}

start() {
    force_log_perms
    service mongod start
    service httpd start

}

stop() {
    service httpd stop
}

restart() {
    force_log_perms
    service mongod start
    service httpd restart
}

status() {
    service mongod status
    service httpd status
}

case "$1" in
    start)
        start
    ;;

    stop)
        stop
    ;;
    status)
        status
    ;;

    restart)
        restart
    ;;

    *)
        echo "Usage: /etc/init.d/report-server {start|stop|restart|status}"
        exit 1
    ;;
esac

exit 0
